from __future__ import annotations

import json
from pathlib import Path


EXECUTION_FLAGS_MANIFEST = Path("data/quant/execution/execution_flags_manifest.json")
EXECUTION_FLAGS_REPORT = Path("data/quant/reports/execution_flags_coverage_latest.md")
FORWARD_LABELS = Path("data/quant/labels/forward_return_labels.jsonl")


def load_jsonl(path: Path) -> list[dict]:
    assert path.exists()
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def test_execution_flags_manifest_json_contract() -> None:
    manifest = json.loads(EXECUTION_FLAGS_MANIFEST.read_text(encoding="utf-8"))
    for field in [
        "schema_version",
        "generated_at",
        "production_impact",
        "inspected_label_count",
        "inspected_price_row_count",
        "suspend_status_availability",
        "limit_up_down_status_availability",
        "failed_order_availability",
        "partial_fill_availability",
        "t_plus_one_policy",
        "cost_policy_reference",
        "execution_realism_status",
        "label_implications",
        "guardrails",
    ]:
        assert field in manifest
    assert manifest["schema_version"] == "1.0"
    assert manifest["production_impact"] == "none"
    assert manifest["inspected_label_count"] > 0
    assert manifest["inspected_price_row_count"] > 0


def test_execution_realism_status_is_not_ready() -> None:
    manifest = json.loads(EXECUTION_FLAGS_MANIFEST.read_text(encoding="utf-8"))
    assert manifest["execution_realism_status"] != "ready"
    assert manifest["execution_realism_status"] == "not_ready_research_only_simulation_execution_data_missing"
    assert manifest["label_implications"]["formal_execution_eligible_allowed"] is False
    assert manifest["label_implications"]["execution_realistic_return_allowed"] is False


def test_execution_data_gaps_are_explicit() -> None:
    manifest = json.loads(EXECUTION_FLAGS_MANIFEST.read_text(encoding="utf-8"))
    assert manifest["suspend_status_availability"]["status"] == "unavailable"
    assert manifest["limit_up_down_status_availability"]["status"] == "unavailable"
    assert manifest["failed_order_availability"]["status"] == "unavailable"
    assert manifest["partial_fill_availability"]["status"] == "deferred"
    for key in [
        "suspend_status_availability",
        "limit_up_down_status_availability",
        "failed_order_availability",
        "partial_fill_availability",
    ]:
        assert manifest[key]["machine_readable_available"] is False
        assert manifest[key]["label_rows_marked_missing"] == manifest["inspected_label_count"]


def test_t_plus_one_policy_is_explicit() -> None:
    manifest = json.loads(EXECUTION_FLAGS_MANIFEST.read_text(encoding="utf-8"))
    policy = manifest["t_plus_one_policy"]
    assert policy["configured_rebalance_rule"] == "daily_after_signal_with_t_plus_1_execution"
    assert policy["primary_entry_model"] == "next_open"
    assert policy["status"] == "research_only_not_execution_realistic"
    assert "not_official_frozen_exchange_calendar" in policy["calendar_source"]


def test_report_states_backtest_remains_research_only_simulation() -> None:
    text = EXECUTION_FLAGS_REPORT.read_text(encoding="utf-8")
    assert "Current backtest remains `research_only_simulation`" in text
    assert "No execution-realistic return can be claimed" in text
    assert "Factor/backtest/health reports are not regenerated by this card" in text


def test_forward_labels_are_not_upgraded_to_formal_execution_eligible() -> None:
    labels = load_jsonl(FORWARD_LABELS)
    assert labels
    assert all(label.get("formal_execution_eligible") is False for label in labels)
    assert all("execution_realistic_return" not in label for label in labels)
    assert all("execution_flags" not in label for label in labels)
    for flag in ["suspend_status", "limit_up_down_status", "failed_order", "partial_fill"]:
        assert all(flag in (label.get("execution_data_missing") or []) for label in labels)
