from __future__ import annotations

from dataclasses import dataclass

from .contracts import BLOCKED_CAPABILITIES, ResearchStatus
from .manifest import AdapterLayer, FreeSourceProvider, PitAsOfStatus, ProviderRole


@dataclass(frozen=True)
class ProviderFieldMapping:
    provider: FreeSourceProvider
    provider_role: ProviderRole
    adapter_layer: AdapterLayer
    endpoint: str
    raw_field: str
    canonical_candidate: str
    value_type: str
    unit: str
    pit_asof_status: PitAsOfStatus
    research_status: ResearchStatus
    formal_allowed: bool
    notes: str


BAOSTOCK_FIELD_MAPPINGS: tuple[ProviderFieldMapping, ...] = (
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.CALENDAR,
        "query_trade_dates",
        "calendar_date",
        "trade_calendar.date",
        "date_string",
        "calendar_day",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Trading calendar candidate; requires official holiday cross-check before any formal use.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.CALENDAR,
        "query_trade_dates",
        "is_trading_day",
        "trade_calendar.is_open",
        "boolean_like_string",
        "flag",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Provider trading-day flag; non-production date alignment only.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.STOCK_BASIC,
        "query_stock_basic",
        "code",
        "security.code",
        "string",
        "provider_code",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Provider code identity metadata.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.STOCK_BASIC,
        "query_stock_basic",
        "code_name",
        "security.name",
        "string",
        "name",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Security name can be revised; metadata candidate only.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.STOCK_BASIC,
        "query_stock_basic",
        "ipoDate",
        "security.list_date",
        "date_string",
        "calendar_day",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Listing date candidate; requires historical status audit before formal use.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.STOCK_BASIC,
        "query_stock_basic",
        "outDate",
        "security.delist_date",
        "date_string_or_empty",
        "calendar_day",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.PARTIAL,
        False,
        "Nullable delisting date; empty values are expected for active securities.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.STOCK_BASIC,
        "query_stock_basic",
        "type",
        "security.type",
        "provider_enum_string",
        "provider_enum",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Provider enum requires documented meaning before downstream use.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.STOCK_BASIC,
        "query_stock_basic",
        "status",
        "security.list_status",
        "provider_enum_string",
        "provider_enum",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.AVAILABLE,
        False,
        "Listing status metadata candidate; historical revision risk remains.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.RAW_DAILY,
        "query_history_k_data_plus",
        "date",
        "daily.date",
        "date_string",
        "trading_day",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.AVAILABLE,
        False,
        "Raw daily date candidate.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.RAW_DAILY,
        "query_history_k_data_plus",
        "code",
        "daily.code",
        "string",
        "provider_code",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.AVAILABLE,
        False,
        "Raw daily provider code candidate.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.RAW_DAILY,
        "query_history_k_data_plus",
        "open/high/low/close",
        "daily.open/high/low/close",
        "decimal_string",
        "cny_price",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.AVAILABLE,
        False,
        "Raw OHLC candidate; no formal price dataset output.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.RAW_DAILY,
        "query_history_k_data_plus",
        "preclose",
        "daily.pre_close",
        "decimal_string",
        "cny_price",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.AVAILABLE,
        False,
        "Previous close field candidate.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.RAW_DAILY,
        "query_history_k_data_plus",
        "volume/amount",
        "daily.volume/amount",
        "decimal_string",
        "provider_unit",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.AVAILABLE,
        False,
        "Liquidity fields are not execution fill evidence.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.RAW_DAILY,
        "query_history_k_data_plus",
        "turn/pctChg",
        "daily.turnover/pct_change",
        "decimal_string",
        "provider_unit",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Auxiliary raw daily fields; report-only diagnostics.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.QFQ_CANDIDATE,
        "query_history_k_data_plus",
        "adjustflag",
        "adjustment.requested_policy",
        "provider_enum_string",
        "adjustment_policy",
        PitAsOfStatus.NOT_PIT_READY,
        ResearchStatus.RESEARCH_ONLY,
        False,
        "QFQ request policy metadata; no independent factor revision.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.QFQ_CANDIDATE,
        "query_history_k_data_plus",
        "qfq open/high/low/close",
        "adjusted_daily.qfq_open/high/low/close",
        "decimal_string",
        "adjusted_price",
        PitAsOfStatus.NOT_PIT_READY,
        ResearchStatus.RESEARCH_ONLY,
        False,
        "QFQ price candidate only; formal adjusted return remains blocked.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.INDEX_DAILY,
        "query_history_k_data_plus",
        "date/code/open/high/low/close/preclose",
        "index_daily.date/code/open/high/low/close/pre_close",
        "decimal_string",
        "index_point",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "HS300 / CSI500 index field candidate; no formal benchmark return.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.INDEX_DAILY,
        "query_history_k_data_plus",
        "volume/amount/pctChg",
        "index_daily.volume/amount/pct_change",
        "decimal_string",
        "provider_unit",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Index diagnostic fields; units require confirmation.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.TRADESTATUS_ISST,
        "query_history_k_data_plus",
        "tradestatus",
        "execution_candidate.trade_status",
        "provider_enum_string",
        "flag",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Daily status candidate only; not proof of actual execution.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.BAOSTOCK,
        ProviderRole.PRIMARY,
        AdapterLayer.TRADESTATUS_ISST,
        "query_history_k_data_plus",
        "isST",
        "execution_candidate.is_st",
        "provider_enum_string",
        "flag",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "ST flag candidate; rule version audit remains required.",
    ),
)


AKSHARE_FIELD_MAPPINGS: tuple[ProviderFieldMapping, ...] = (
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.CROSS_CHECK,
        AdapterLayer.RAW_DAILY,
        "stock_zh_a_hist",
        "日期/股票代码",
        "daily.date/code",
        "date_string_and_string",
        "trading_day_and_plain_code",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Stock daily identity fields for cross-check only.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.CROSS_CHECK,
        AdapterLayer.RAW_DAILY,
        "stock_zh_a_hist",
        "开盘/收盘/最高/最低",
        "daily.open/close/high/low",
        "numeric",
        "cny_price",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Raw OHLC cross-check candidate; does not replace BaoStock primary.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.CROSS_CHECK,
        AdapterLayer.RAW_DAILY,
        "stock_zh_a_hist",
        "成交量/成交额/振幅/涨跌幅/涨跌额/换手率",
        "daily.volume/amount/amplitude/pct_change/change/turnover",
        "numeric",
        "provider_unit",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Auxiliary daily fields for cross-check and diagnostics.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.CROSS_CHECK,
        AdapterLayer.QFQ_CANDIDATE,
        "stock_zh_a_hist",
        'adjust="qfq"',
        "adjustment.requested_policy",
        "string",
        "adjustment_policy",
        PitAsOfStatus.NOT_PIT_READY,
        ResearchStatus.RESEARCH_ONLY,
        False,
        "QFQ request metadata; provider/network instability observed in POC.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.CROSS_CHECK,
        AdapterLayer.QFQ_CANDIDATE,
        "stock_zh_a_hist",
        "qfq 开盘/收盘/最高/最低",
        "adjusted_daily.qfq_open/close/high/low",
        "numeric",
        "adjusted_price",
        PitAsOfStatus.NOT_PIT_READY,
        ResearchStatus.RESEARCH_ONLY,
        False,
        "QFQ price cross-check only; no factor revision.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.SUPPLEMENT,
        AdapterLayer.INDEX_DAILY,
        "stock_zh_index_hist_csindex",
        "日期/指数代码",
        "index_daily.date/code",
        "date_string_and_string",
        "trading_day_and_index_code",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "CSIndex endpoint supplement for HS300 / CSI500 identity fields.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.SUPPLEMENT,
        AdapterLayer.INDEX_DAILY,
        "stock_zh_index_hist_csindex",
        "开盘/最高/最低/收盘",
        "index_daily.open/high/low/close",
        "numeric",
        "index_point",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Index OHLC supplement; formal excess return remains blocked.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.SUPPLEMENT,
        AdapterLayer.INDEX_DAILY,
        "stock_zh_index_hist_csindex",
        "成交量/成交金额/涨跌/涨跌幅",
        "index_daily.volume/amount/change/pct_change",
        "numeric",
        "provider_unit",
        PitAsOfStatus.PIT_WEAK,
        ResearchStatus.CANDIDATE,
        False,
        "Index amount field mapping needs unit confirmation.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.SUPPLEMENT,
        AdapterLayer.SUSPEND_EVENT,
        "stock_tfp_em",
        "代码/名称",
        "suspend_event.code/name",
        "string",
        "security_identity",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.PARTIAL,
        False,
        "Event-only suspend identity fields.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.SUPPLEMENT,
        AdapterLayer.SUSPEND_EVENT,
        "stock_tfp_em",
        "停牌时间/停牌截止时间/预计复牌时间",
        "suspend_event.start_date/end_date/expected_resume_date",
        "date_string_or_empty",
        "calendar_day",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.PARTIAL,
        False,
        "Event dates require daily expansion before comparison with tradestatus.",
    ),
    ProviderFieldMapping(
        FreeSourceProvider.AKSHARE,
        ProviderRole.SUPPLEMENT,
        AdapterLayer.SUSPEND_EVENT,
        "stock_tfp_em",
        "停牌期限/停牌原因/所属市场",
        "suspend_event.duration/reason/market",
        "string",
        "event_metadata",
        PitAsOfStatus.AS_COLLECTED_ONLY,
        ResearchStatus.PARTIAL,
        False,
        "Event-only metadata; not daily execution eligibility.",
    ),
)


PROVIDER_FIELD_MAPPINGS: tuple[ProviderFieldMapping, ...] = (
    *BAOSTOCK_FIELD_MAPPINGS,
    *AKSHARE_FIELD_MAPPINGS,
)


BLOCKED_MAPPING_CAPABILITIES = frozenset(
    capability.capability
    for capability in BLOCKED_CAPABILITIES
    if capability.status is ResearchStatus.BLOCKED
)
