from __future__ import annotations

from typing import Any


FeatureUsage = dict[str, Any]


_USAGE: dict[str, FeatureUsage] = {
    "trade_calendar": {
        "label": "交易日历",
        "group": "formal_guardrail",
        "decision_use": "hard_gate",
        "live_permission": "formal_candidate",
        "intended_surfaces": ["settings"],
        "explanation": "正式交易日对齐和非交易日降级，不参与排序。",
    },
    "bars.daily": {
        "label": "正式日线",
        "group": "formal_guardrail",
        "decision_use": "hard_gate",
        "live_permission": "formal_candidate",
        "intended_surfaces": ["settings", "discovery", "decision_ledger"],
        "explanation": "价格和复权底座，真钱闸门只认 formal manifest。",
    },
    "adjustment.factor": {
        "label": "复权因子",
        "group": "formal_guardrail",
        "decision_use": "hard_gate",
        "live_permission": "formal_candidate",
        "intended_surfaces": ["settings"],
        "explanation": "复权价格校验，用于正式底座完整性。",
    },
    "benchmark.index_daily": {
        "label": "指数日线",
        "group": "formal_guardrail",
        "decision_use": "hard_gate",
        "live_permission": "formal_candidate",
        "intended_surfaces": ["settings", "decision_ledger"],
        "explanation": "基准对照和市场状态校验。",
    },
    "price_limit.daily": {
        "label": "涨跌停价",
        "group": "formal_guardrail",
        "decision_use": "hard_gate",
        "live_permission": "formal_candidate",
        "intended_surfaces": ["settings", "discovery"],
        "explanation": "执行约束数据，只用于正式执行安全检查。",
    },
    "execution.flags": {
        "label": "执行标记",
        "group": "formal_guardrail",
        "decision_use": "hard_gate",
        "live_permission": "formal_candidate",
        "intended_surfaces": ["settings", "discovery"],
        "explanation": "ST/停牌/涨跌停等硬约束，不给排序加分。",
    },
    "valuation.daily": {
        "label": "估值历史",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "PE/PB/市值进入因子评分和解释，只做观察池排序微调。",
    },
    "liquidity.daily": {
        "label": "流动性历史",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "换手和量比用于流动性因子，不放大真钱权限。",
    },
    "capital_flow.daily": {
        "label": "资金流历史",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "主力净流入用于资金面因子和入池解释。",
    },
    "fundamentals.snapshot": {
        "label": "基本面快照",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "基本面摘要补足质量因子和证据层。",
    },
    "financial.indicator": {
        "label": "财务指标",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "ROE、负债率和利润率用于质量因子。",
    },
    "financial.statement": {
        "label": "财务报表",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "收入、资产和现金流作为只读财务证据展示。",
    },
    "corporate_action.dividend": {
        "label": "分红送配",
        "group": "review_only",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "公司行为证据，暂不参与排序或真钱闸门。",
    },
    "shareholder.top10": {
        "label": "前十大股东",
        "group": "review_only",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "股东结构证据，辅助人工复核。",
    },
    "market.limit_events": {
        "label": "涨跌停事件",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "discovery", "decision_ledger"],
        "explanation": "市场情绪和异常波动提示，主要用于风险提示。",
    },
    "index.weight": {
        "label": "指数成分权重",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "核心指数成分作为稳定性标签和因子贡献。",
    },
    "market.daily_basic_snapshot": {
        "label": "全市场日指标",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery"],
        "explanation": "全市场估值和市值快照，作为个股估值兜底证据。",
    },
    "market.margin": {
        "label": "两融总量",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "杠杆情绪背景，用于风险提醒和因子快照。",
    },
    "market.top_list": {
        "label": "龙虎榜",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "异常交易既可解释强势，也触发短线脉冲风险。",
    },
    "market.top_inst": {
        "label": "龙虎榜机构席位",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "机构席位净买作为正向标签，但仍受短线风险约束。",
    },
    "market.hsgt_moneyflow": {
        "label": "北向/南向资金",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "跨境资金强弱作为市场背景和标签。",
    },
    "market.ggt_daily": {
        "label": "港股通日汇总",
        "group": "reference",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings"],
        "explanation": "港股通成交背景，目前只在资产盘点展示。",
    },
    "reference.stock_company": {
        "label": "公司画像",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "注册地址、主营和上市信息用于看懂公司，不参与真钱放行。",
    },
    "reference.namechange": {
        "label": "名称变更",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "历史简称和更名记录用于识别公司沿革。",
    },
    "reference.concept": {
        "label": "概念字典",
        "group": "reference",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings"],
        "explanation": "概念字典本身只提供标签解释。",
    },
    "reference.concept_detail": {
        "label": "概念归属",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "热门概念用于主题标签和排序解释，权重保持保守。",
    },
    "reference.industry_classify": {
        "label": "行业分类",
        "group": "reference",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings"],
        "explanation": "行业树只做归因字典。",
    },
    "reference.industry_member": {
        "label": "行业成分",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "申万行业归属用于公司画像和行业证据。",
    },
    "reference.ths_index": {
        "label": "同花顺板块",
        "group": "reference",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings"],
        "explanation": "板块字典用于解释成员归属。",
    },
    "reference.ths_member": {
        "label": "同花顺成分",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "同花顺板块归属作为主题证据。",
    },
    "reference.dc_index": {
        "label": "东财板块",
        "group": "reference",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings"],
        "explanation": "东财板块字典用于解释成员归属。",
    },
    "reference.dc_member": {
        "label": "东财成分",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "东财板块归属作为主题证据。",
    },
    "financial.main_business": {
        "label": "主营构成",
        "group": "stock_profile",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "decision_ledger", "ask"],
        "explanation": "主营构成用于业务质量和集中度标签，暂不作为硬排序分。",
    },
    "market.margin_detail": {
        "label": "两融明细",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "个股融资余额变化用于识别过热或撤退风险。",
    },
    "market.margin_secs": {
        "label": "两融标的",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "decision_ledger"],
        "explanation": "标的状态用于解释两融可交易性和风险背景。",
    },
    "market.block_trade": {
        "label": "大宗交易",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "大宗折价和成交额触发供给压力风险提示。",
    },
    "market.hsgt_top10": {
        "label": "陆股通十大",
        "group": "review_only",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile"],
        "explanation": "北向活跃成交证据，暂不参与排序。",
    },
    "market.ggt_top10": {
        "label": "港股通十大",
        "group": "review_only",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings"],
        "explanation": "南向活跃成交证据，暂只展示。",
    },
    "corporate_action.pledge_stat": {
        "label": "质押统计",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "股权质押比例和趋势形成风险标签。",
    },
    "corporate_action.pledge_detail": {
        "label": "质押明细",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "decision_ledger", "ask"],
        "explanation": "质押事件明细辅助解释质押风险。",
    },
    "corporate_action.share_float": {
        "label": "限售解禁",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "解禁规模和时间窗口形成供给压力风险。",
    },
    "corporate_action.repurchase": {
        "label": "股份回购",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "回购进展可作为支撑标签，但不直接制造买入信号。",
    },
    "financial.audit": {
        "label": "审计意见",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "非标审计意见触发审计异常风险。",
    },
    "research.report_rc": {
        "label": "研报评级",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger", "ask"],
        "explanation": "评级和目标价变化用于预期上修/下修标签。",
    },
    "technical.stk_factor": {
        "label": "技术因子",
        "group": "factor",
        "decision_use": "ranking_signal",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "技术指标摘要用于因子快照和短线解释。",
    },
    "technical.cyq_perf": {
        "label": "筹码表现",
        "group": "risk_event",
        "decision_use": "risk_penalty",
        "live_permission": "research_only",
        "intended_surfaces": ["settings", "stock_profile", "discovery", "decision_ledger"],
        "explanation": "筹码盈利/集中变化用于筹码压力风险。",
    },
    "technical.cyq_chips": {
        "label": "筹码明细",
        "group": "review_only",
        "decision_use": "evidence_only",
        "live_permission": "display_only",
        "intended_surfaces": ["settings", "stock_profile", "ask"],
        "explanation": "筹码明细数据量大，当前只保留证据摘要。",
    },
}


def feature_usage(dataset: str) -> FeatureUsage:
    usage = _USAGE.get(dataset, {})
    return {
        "dataset": dataset,
        "label": usage.get("label") or dataset,
        "group": usage.get("group") or "review_only",
        "decision_use": usage.get("decision_use") or "evidence_only",
        "live_permission": usage.get("live_permission") or "display_only",
        "intended_surfaces": list(usage.get("intended_surfaces") or ["settings"]),
        "explanation": usage.get("explanation") or "只读资产盘点，尚未进入正式能力层。",
    }


def feature_usage_map() -> dict[str, FeatureUsage]:
    return {dataset: feature_usage(dataset) for dataset in sorted(_USAGE)}
